HERO_BY_SLUG = {
    'laptop-mot-wickford-essex': ('/assets/images/image-50e35116.webp', 'Laptop battery service on the LaunchLayer Wickford bench'),
    'laptop-mot-wickford': ('/assets/images/image-4307083f.png', 'LaunchLayer Wickford workshop bench ready for a laptop MOT'),
    'wickford-laptop-repair': ('/assets/images/image-d26fc546.png', 'Wickford in Bloom — LaunchLayer’s home town'),
    'wickford-pc-repair': ('/assets/images/towns/wickford-town.jpg', 'Wickford — local PC repair from our Glebe Road workshop'),
    'liquid-damage-repair-wickford': ('/assets/images/image-e1658f14.webp', 'Ultrasonic cleaning tank for liquid damage recovery — LaunchLayer Wickford'),
    'data-recovery': ('/assets/images/image-ce1e457a.jpg', 'Open hard drive platter and read head — data recovery'),
    'custom-pc-builds': ('/assets/images/image-ddefba94.webp', 'Custom gaming PC built at LaunchLayer Wickford'),
    'eco-recycling': ('/assets/images/image-eco-donate-hero.jpg', 'Laptop donation for children — LaunchLayer recycling partnership'),
    'wickford-virus-removal': ('/assets/images/image-23ca3c6b.webp', 'Full malware scan completed on a customer laptop — LaunchLayer Wickford'),
    'laptop-screen-repair-wickford': ('/assets/images/image-c7fb44a8.webp', 'Laptop screen replacement in progress — LaunchLayer Wickford'),
    'macbook-repair': ('/assets/images/image-c27f7c59.jpg', 'Open MacBook Pro showing fan, logic board and battery'),
    'macbook-repair-wickford': ('/assets/images/image-69f0c879.jpg', 'Silver MacBook on desk — Wickford MacBook repair'),
    'basildon-pc-repair': ('/assets/images/towns/basildon-town.jpg', 'Basildon town square — local PC & laptop repair coverage'),
    'billericay-pc-repair': ('/assets/images/towns/billericay-town.jpg', 'Billericay High Street — local PC & laptop repair coverage'),
    'brentwood-pc-repair': ('/assets/images/towns/brentwood-town.jpg', 'Brentwood High Street — local PC & laptop repair coverage'),
    'chelmsford-pc-repair': ('/assets/images/towns/chelmsford-town.jpg', 'Chelmsford High Street — local PC & laptop repair coverage'),
    'southend-pc-repair': ('/assets/images/towns/southend-town.jpg', 'Southend High Street — local PC & laptop repair coverage'),
    'rayleigh-laptop-service': ('/assets/images/towns/rayleigh-town.jpg', 'Rayleigh High Street — local laptop service coverage'),
    'macbook-repair-basildon': ('/assets/images/image-c27f7c59.jpg', 'Open MacBook Pro internals — Basildon MacBook repair'),
    'liquid-damage-repair-basildon': ('/assets/images/image-e1658f14.webp', 'Ultrasonic cleaning tank for liquid damage recovery — LaunchLayer (Basildon)'),
    'brands-supported': ('/assets/files/photo-1588872657578-7efd1f1555ed', 'Dell and Windows laptop — brands and devices LaunchLayer repairs'),
}
